name: Simple Reusable

on:
  workflow_call:   # THIS makes it reusable

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from reusable workflow
        run: echo "Hello from MLOps Demo reusable workflow!"
